version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: runApp.py
      FLASK_ENV: development
      DATABASE_URI: mysql+pymysql://${DB_USER}:${DB_PWD}@${DB_URL}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql_data:
