"""Initial migration.

Revision ID: 22cca38920bb
Revises: c9ab42396af1
Create Date: 2024-08-09 22:13:54.624157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cca38920bb'
down_revision = 'c9ab42396af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate')
    # ### end Alembic commands ###
