"""user model.

Revision ID: 4a64cddff480
Revises: afbeb79eccaa
Create Date: 2024-07-27 00:04:52.102234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a64cddff480'
down_revision = 'afbeb79eccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_training', schema=None) as batch_op:
        batch_op.drop_constraint('employee_training_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('employee_training_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['e_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'training', ['t_id'], ['training_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_training', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employee_training_ibfk_2', 'training', ['t_id'], ['training_id'])
        batch_op.create_foreign_key('employee_training_ibfk_1', 'employee', ['e_id'], ['id'])

    # ### end Alembic commands ###
