"""Initial migration.

Revision ID: 7ce62ebbbdbf
Revises: c8e47d7ffc42
Create Date: 2024-07-10 22:10:36.486907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ce62ebbbdbf'
down_revision = 'c8e47d7ffc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('salary_range',
               existing_type=mysql.INTEGER(),
               type_=mysql.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('salary_range',
               existing_type=mysql.JSON(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
