"""Initial migration.

Revision ID: c9ab42396af1
Revises: f697570fc999
Create Date: 2024-08-08 19:16:47.594524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ab42396af1'
down_revision = 'f697570fc999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('going_id', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('comming_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'path', ['going_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'path', ['comming_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'comming_id')
    op.drop_column('employee', 'going_id')
    # ### end Alembic commands ###
