"""Initial migration.

Revision ID: f697570fc999
Revises: 3b44678270bc
Create Date: 2024-08-08 19:15:46.624435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f697570fc999'
down_revision = '3b44678270bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path')
    # ### end Alembic commands ###
